printn: printnumbers.c
	gcc printnumbers.c -o printnumbers

primes: primes.c
	gcc primes.c -o primes

allprimes: printn primes
	./printnumbers | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes